### ISSUE TITLE
Nonexistant folder in dockerfile

### ISSUE THREAD

**Issue by oliverdutton** [PeptoneLtd/ADOPT#38]
[In the `Dockerfiles/Dockerfile_adopt_mac_m1`](https://github.com/PeptoneLtd/ADOPT/blob/dev/Dockerfiles/Dockerfile_adopt_mac_m1) the folder `esm_models` is copied, but this folder is not in the repo.

**Comment by CFisicaro** [comment]
Yeah that was a test, I have to update it without the directory.
Feel free to use [this](https://github.com/PeptoneLtd/ADOPT/blob/dev/Dockerfiles/Dockerfile_adopt_mac_m1) docker file without the COPY statement in the meantime.
